//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wagenpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boekingen
    {
        public int Boekingid { get; set; }
        public int gastID { get; set; }
        public int lodgeID { get; set; }
        public System.DateTime incheckdatum { get; set; }
        public System.DateTime uitcheckdatum { get; set; }
        public int aantalnachten
        {
            get
            {
                DateTime start = incheckdatum;
                DateTime end = uitcheckdatum;

                return ((int)(end - start).TotalDays);

            }




        }


        public virtual Gasten Gasten { get; set; }
        public virtual Lodges Lodges { get; set; }
    }
}
