//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wagenpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lodges
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lodges()
        {
            this.Boekingen = new HashSet<Boekingen>();
        }
    
        public int LodgeID { get; set; }
        public int LodgeTypeID { get; set; }
        public int LodgeNR { get; set; }
        public string LodgeNaam { get; set; }
        public bool Bezettingsgraad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boekingen> Boekingen { get; set; }
        public virtual LodgeTypes LodgeTypes { get; set; }
    }
}
