//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wagenpark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LodgeTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LodgeTypes()
        {
            this.Lodges = new HashSet<Lodges>();
        }
    
        public int LodgeTypeID { get; set; }
        public string LodgeTypeNaam { get; set; }
        public string LodgeOmschrijving { get; set; }
        public int aantalpersonen { get; set; }
        public decimal prijs { get; set; }
        public string url { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lodges> Lodges { get; set; }
    }
}
